# Generated by Django 5.2.12 on 2026-03-06 19:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_service', '0002_vendor_subscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20)),
                ('otp_code', models.CharField(max_length=6)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('expired', 'Expired'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('attempts', models.IntegerField(default=0)),
                ('max_attempts', models.IntegerField(default=5)),
                ('is_used', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'otp_verifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['phone_number', 'status'], name='otp_verific_phone_n_e06d33_idx'), models.Index(fields=['expires_at'], name='otp_verific_expires_e91cd1_idx')],
            },
        ),
        migrations.CreateModel(
            name='DeliveryAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=20)),
                ('address_line1', models.CharField(max_length=255)),
                ('address_line2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=100)),
                ('address_type', models.CharField(choices=[('home', 'Home'), ('work', 'Work'), ('other', 'Other')], default='home', max_length=20)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_delivery_addresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_service_delivery_addresses',
                'ordering': ['-is_default', '-created_at'],
                'unique_together': {('user', 'is_default')},
            },
        ),
        migrations.CreateModel(
            name='OTPLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20)),
                ('action', models.CharField(choices=[('sent', 'OTP Sent'), ('verified', 'OTP Verified'), ('failed', 'OTP Failed'), ('expired', 'OTP Expired')], max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('otp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_service.otpverification')),
            ],
            options={
                'db_table': 'otp_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['phone_number', 'action'], name='otp_logs_phone_n_2d5325_idx'), models.Index(fields=['created_at'], name='otp_logs_created_a44226_idx')],
            },
        ),
    ]
