# Generated by Django 6.0.2 on 2026-03-03 17:39

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product_service', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('minimum_rating', models.IntegerField(default=1)),
                ('maximum_rating', models.IntegerField(default=5)),
                ('minimum_title_length', models.IntegerField(default=10)),
                ('minimum_body_length', models.IntegerField(default=20)),
                ('require_verified_purchase', models.BooleanField(default=False)),
                ('auto_approve_verified', models.BooleanField(default=True)),
                ('require_one_image_for_low_rating', models.BooleanField(default=False)),
                ('block_keywords', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'review_policies',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '1 Star'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('quality_rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('value_rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('shipping_rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('images', models.JSONField(default=list, help_text='URLs of uploaded images')),
                ('video_url', models.URLField(blank=True, null=True)),
                ('status', models.CharField(choices=[('published', 'Published'), ('pending', 'Pending Moderation'), ('rejected', 'Rejected'), ('hidden', 'Hidden')], default='pending', max_length=20)),
                ('rejection_reason', models.TextField(blank=True)),
                ('helpful_count', models.IntegerField(default=0)),
                ('unhelpful_count', models.IntegerField(default=0)),
                ('seller_response', models.TextField(blank=True)),
                ('seller_response_at', models.DateTimeField(blank=True, null=True)),
                ('is_verified_purchase', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detailed_reviews', to='product_service.product')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detailed_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reviews',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewHelpful',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_type', models.CharField(choices=[('helpful', 'Helpful'), ('unhelpful', 'Unhelpful')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='review_service.review')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'review_helpful',
            },
        ),
        migrations.CreateModel(
            name='ReviewModerationQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=200)),
                ('priority', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderation_queue', to=settings.AUTH_USER_MODEL)),
                ('review', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='moderation_queue', to='review_service.review')),
            ],
            options={
                'db_table': 'review_moderation_queue',
                'ordering': ['-priority', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=50)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='review_service.review')),
            ],
            options={
                'db_table': 'review_tags',
            },
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['product', 'status'], name='reviews_product_f784a6_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['reviewer'], name='reviews_reviewe_965d53_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['-helpful_count'], name='reviews_helpful_b761c2_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['is_verified_purchase'], name='reviews_is_veri_a85f3b_idx'),
        ),
        migrations.AddIndex(
            model_name='reviewhelpful',
            index=models.Index(fields=['review', 'vote_type'], name='review_help_review__d7dddc_idx'),
        ),
        migrations.AddConstraint(
            model_name='reviewhelpful',
            constraint=models.UniqueConstraint(fields=('review', 'user'), name='unique_review_user_vote'),
        ),
        migrations.AddConstraint(
            model_name='reviewtag',
            constraint=models.UniqueConstraint(fields=('review', 'tag'), name='unique_review_tag'),
        ),
    ]
