# Generated by Django 6.0.2 on 2026-03-03 17:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product_service', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_public', models.BooleanField(default=False)),
                ('share_token', models.CharField(blank=True, max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'wishlists',
            },
        ),
        migrations.CreateModel(
            name='WishlistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_when_added', models.DecimalField(decimal_places=2, max_digits=10)),
                ('current_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notify_on_price_drop', models.BooleanField(default=True)),
                ('notify_on_sale', models.BooleanField(default=True)),
                ('notify_back_in_stock', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, help_text="User's personal notes")),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_wishlists', to='product_service.product')),
                ('wishlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='wishlist_service.wishlist')),
            ],
            options={
                'db_table': 'wishlist_items',
            },
        ),
        migrations.CreateModel(
            name='WishlistNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('price_drop', 'Price Drop'), ('on_sale', 'On Sale'), ('back_in_stock', 'Back in Stock')], max_length=20)),
                ('old_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('new_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='wishlist_service.wishlistitem')),
            ],
            options={
                'db_table': 'wishlist_notifications',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='WishlistShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shared_with_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('shared_at', models.DateTimeField(auto_now_add=True)),
                ('shared_with_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shared_wishlists', to=settings.AUTH_USER_MODEL)),
                ('wishlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='wishlist_service.wishlist')),
            ],
            options={
                'db_table': 'wishlist_shares',
            },
        ),
        migrations.AddIndex(
            model_name='wishlistitem',
            index=models.Index(fields=['wishlist', 'added_at'], name='wishlist_it_wishlis_8e1536_idx'),
        ),
        migrations.AddConstraint(
            model_name='wishlistitem',
            constraint=models.UniqueConstraint(fields=('wishlist', 'product'), name='unique_wishlist_product'),
        ),
    ]
