# Generated by Django 5.2.12 on 2026-03-07 00:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_service', '0003_order_escrow_status_order_estimated_delivery_and_more'),
        ('returns_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returnshipment',
            name='return_request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shipment', to='order_service.returnrequest'),
        ),
        migrations.AlterField(
            model_name='returnhistory',
            name='return_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='order_service.returnrequest'),
        ),
        migrations.DeleteModel(
            name='ReturnRequest',
        ),
    ]
