# Generated by Django 5.2.12 on 2026-03-07 00:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_service', '0003_product_media_and_variants'),
        ('search_service', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserEngagementMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_searches', models.IntegerField(default=0)),
                ('total_views', models.IntegerField(default=0)),
                ('total_adds_to_cart', models.IntegerField(default=0)),
                ('total_wishlist_adds', models.IntegerField(default=0)),
                ('total_purchases', models.IntegerField(default=0)),
                ('total_reviews', models.IntegerField(default=0)),
                ('engagement_score', models.FloatField(default=0.0, help_text='0-100 scale')),
                ('avg_session_duration', models.IntegerField(default=0, help_text='seconds')),
                ('last_activity_at', models.DateTimeField(blank=True, null=True)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='engagement_metric', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_engagement_metrics',
            },
        ),
        migrations.CreateModel(
            name='BrowsingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_count', models.IntegerField(default=1)),
                ('last_viewed_at', models.DateTimeField(auto_now=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='browsed_by', to='product_service.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='browsing_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'browsing_history',
                'indexes': [models.Index(fields=['user', 'last_viewed_at'], name='browsing_hi_user_id_667cca_idx')],
                'unique_together': {('user', 'product')},
            },
        ),
        migrations.CreateModel(
            name='ProductInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_type', models.CharField(choices=[('view', 'Product View'), ('click', 'Click'), ('add_to_cart', 'Add to Cart'), ('add_to_wishlist', 'Add to Wishlist'), ('remove_from_wishlist', 'Remove from Wishlist'), ('share', 'Share'), ('review', 'Review/Rate'), ('report', 'Report'), ('purchase', 'Purchase'), ('compare', 'Compare'), ('zoom_image', 'Zoom Image'), ('read_review', 'Read Review')], max_length=20)),
                ('interaction_value', models.CharField(blank=True, help_text='Additional data about the interaction', max_length=255)),
                ('page', models.CharField(blank=True, help_text='Page where interaction occurred', max_length=100)),
                ('referrer', models.CharField(blank=True, max_length=255)),
                ('device_type', models.CharField(choices=[('mobile', 'Mobile'), ('tablet', 'Tablet'), ('desktop', 'Desktop')], default='desktop', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='product_service.product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_interactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'product_interactions',
                'indexes': [models.Index(fields=['product', 'interaction_type', 'created_at'], name='product_int_product_2a8be4_idx'), models.Index(fields=['user', 'interaction_type', 'created_at'], name='product_int_user_id_d9f495_idx'), models.Index(fields=['created_at'], name='product_int_created_5e3bab_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProductView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(blank=True, max_length=100)),
                ('view_duration', models.IntegerField(default=0, help_text='Time spent viewing product in seconds')),
                ('source', models.CharField(choices=[('search', 'Search Results'), ('category', 'Category Browse'), ('featured', 'Featured Section'), ('recommendation', 'Recommendation'), ('direct', 'Direct Link'), ('other', 'Other')], default='direct', max_length=50)),
                ('device_type', models.CharField(choices=[('mobile', 'Mobile'), ('tablet', 'Tablet'), ('desktop', 'Desktop')], default='desktop', max_length=20)),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='product_service.product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'product_views',
                'indexes': [models.Index(fields=['product', 'viewed_at'], name='product_vie_product_358d3d_idx'), models.Index(fields=['user', 'viewed_at'], name='product_vie_user_id_caee54_idx'), models.Index(fields=['viewed_at'], name='product_vie_viewed__28cb00_idx')],
            },
        ),
    ]
