# Generated by Django 5.2.12 on 2026-04-16 14:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorStorefront',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='URL-safe identifier: /shop/<slug>', max_length=120, unique=True)),
                ('tagline', models.CharField(blank=True, max_length=200)),
                ('banner_url', models.URLField(blank=True, help_text='Hero banner image URL')),
                ('logo_url', models.URLField(blank=True, help_text='Storefront logo URL')),
                ('announcement', models.CharField(blank=True, help_text="Short announcement bar text (e.g. 'Free shipping over $50')", max_length=300)),
                ('template', models.CharField(choices=[('minimal', 'Minimal'), ('bold', 'Bold'), ('elegant', 'Elegant'), ('vibrant', 'Vibrant'), ('tech', 'Tech')], default='minimal', max_length=20)),
                ('primary_color', models.CharField(default='#6366f1', max_length=7)),
                ('secondary_color', models.CharField(default='#f59e0b', max_length=7)),
                ('bg_color', models.CharField(default='#ffffff', max_length=7)),
                ('text_color', models.CharField(default='#111827', max_length=7)),
                ('show_featured_section', models.BooleanField(default=True)),
                ('show_categories_filter', models.BooleanField(default=True)),
                ('show_search_bar', models.BooleanField(default=True)),
                ('products_per_row', models.IntegerField(default=4)),
                ('website_url', models.URLField(blank=True)),
                ('facebook_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('is_published', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vendor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='storefront', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'vendor_storefronts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StorefrontSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type', models.CharField(choices=[('banner', 'Banner'), ('text', 'Text Block'), ('collection', 'Featured Collection'), ('video', 'Video')], max_length=20)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('content', models.TextField(blank=True)),
                ('image_url', models.URLField(blank=True)),
                ('link_url', models.URLField(blank=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('storefront', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='vendor_storefront.vendorstorefront')),
            ],
            options={
                'db_table': 'storefront_sections',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='StorefrontReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('title', models.CharField(blank=True, max_length=200)),
                ('comment', models.TextField()),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor_reviews_given', to=settings.AUTH_USER_MODEL)),
                ('storefront', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_reviews', to='vendor_storefront.vendorstorefront')),
            ],
            options={
                'db_table': 'storefront_reviews',
                'ordering': ['-created_at'],
                'unique_together': {('storefront', 'reviewer')},
            },
        ),
    ]
